version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: install project dependencies
          command: npm install
      - run:
          name: run test
          command: npm run test
