version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm install
      - run: npm start

  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm run test

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
