version: 2.1

orbs:
  node: circleci/node@4.1

workflows:
  build_and_test::
    jobs:
      - build
      - test

jobs:
  build:
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install

  test:
    steps:
      - checkout
      - run:
          name: test
          command: npm run test
