version: 2.1

orbs:
  node: circleci/node@4.1

workflows:
  sample:
    jobs:
      - node/test:
          version: "15.1"
# version: 2.1

# jobs:
#   build:
#     docker:
#       - image: circleci/node:14
#     steps:
#       - checkout
#       - restore_cache:
#           key: dependency-cache-{{ checksum "package.json" }}
#       - run: npm install
#       - save_cache:
#           key: dependency-cache-{{ checksum "package.json" }}
#           paths:
#             - ./node_modules
#       - run: npm start
#       - run: npm run test

# workflows:
#   build:
#     jobs:
#       - build
